version: '3.7'
services:
  api:
    container_name: commerce-server-api
    build: ./
    restart: alwaysw
    image: commerce-server-api
    ports:
      - 5469:4444
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  db:
    container_name: commerce-server-db
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: commerce
      POSTGRES_PASSWORD: Y29tbWVyY2Utc2VuaGEtZGItZm9kYQ
      POSTGRES_DB: commerce

  redis:
    build: redis/.
    restart: always
    command: redis-server
    ports:
      - 6828:6379
    container_name: commerce-server-redis
