version: '3.7'
services:
  db:
    container_name: commerce-server-db
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # networks:
    #   - commerce-server-network
  api:
    container_name: commerce-server-api
    build: ./
    restart: always
    image: commerce-server-api
    ports:
      - 4444:4444
    depends_on:
      - db
    links:
      - db
    # networks:
    #   - commerce-server-network
# networks:
#   commerce-server-network:
#     driver: bridge
